version: "3"
services:
  airdna:
    container_name: airdna
    image: 192.168.1.32:5555/airdna
    ports:
      - 30000:3000
    volumes:
      - .:/root
    networks:
      - public
    command:
      - /root/docker/startup.sh
networks:
  public:
  private:
volumes:
  back-notused:
  db-data: